# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo apt-get install jags

install:
  - ./travis-tool.sh install_aptget r-cran-knitr r-cran-ggplot2 r-cran-dplyr r-cran-rjags r-cran-coda
  - ./travis-tool.sh install_github hadley/reshape rstudio/rmarkdown benmarwick/Pleistocene-aged-stone-artefacts-from-Jerimalai--East-Timor
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
  - WARNINGS_ARE_ERRORS=0

notifications:
  email:
    on_success: change
    on_failure: change
